FROM willsonic/ws-nginx-alpine:v0.0.1


RUN mkdir -p /tmp/nginx/client-body
RUN mkdir -p /etc-dev/nginx
RUN mkdir -p /var/cache/nginx/api

COPY ./etc-dev/nginx.conf /etc-dev/nginx/nginx.conf


CMD ["nginx", "-g", "daemon off;"]